### ISSUE TITLE
Crash: Crash on weapon select

### ISSUE THREAD

**Issue by mm12** [NatoBoram/switcheroo#18]
Every time I click a mob, switcharoo causes a crash. 

Crash log of one instance of this (w/ some info redacted) attached. The crash reason is `java.lang.NoSuchMethodError: 'net.minecraft.class_1310 net.minecraft.class_1309.method_6046()'`
[mcCrashSwitcharoo.txt](https://github.com/user-attachments/files/15941976/mcCrashSwitcharoo.txt)

**Comment by NatoBoram** [comment]
Thanks!

I have modified the version compatibility in Modrinth. Switcheroo v1.0.13 is compatible with Minecraft 1.20.1–1.20.4, sorry for the inconvenience.

I'm also trying to update it to 1.21, but Mojang changed the way damage works and I can't figure out how to calculate item damages against specific entities depending on the enchants.

So anyway, I'll close this issue since the problem was the wrong documentation. Weapons will be fixed (or dropped) in https://github.com/NatoBoram/switcheroo/issues/20.
